---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: rewrite-vs
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.92"
  host: rewrite.f5demo.local
  pools:
    - path: /lab
      service: svc-1
      servicePort: 80
      rewrite: /laboratory
    - path: /lib
      service: svc-2
      servicePort: 80
      rewrite: /library
