apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  labels:
    f5cr: "true"
  name: wildcard-tls-vs
  namespace: default
spec:
  host: '*.foo.com'
  tlsProfileName: wildcard-tls
  virtualServerAddress: 10.1.10.116
  virtualServerName: "wildcard-tls-vs"
  httpTraffic: none
  pools:
    - path: /foo
      service: svc-1
      servicePort: 80
  snat: auto

