apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  labels:
    f5cr: "true"
  name: wildcard-tls
  namespace: default
spec:
  hosts:
    - '*.f5demo.local'
  tls:
    clientSSL: /Common/clientssl
    reference: bigip
    termination: edge