apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: tea-virtual-server
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.60"
  host: health.f5demo.local
  pools:
  - path: /foo
    service: app1-svc
    servicePort: 8080
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 3
  - path: /bar
    service: echo-svc
    servicePort: 80
    monitor:
      type: http
      send: “GET /rn”
      recv: ""
      interval: 10
      timeout: 3