---
- name: Deploying DO
  hosts: bigip
  connection: local
  gather_facts: false
  vars:
    provider:
      password: "{{f5_pass}}"
      server: "{{inventory_hostname}}"
      user: "{{f5_user}}"
      validate_certs: no
      server_port: 443
  tasks:
<<<<<<< HEAD

=======
>>>>>>> d0249d3c076f215d08406e227e520a8292cd0969
  - name: Wait for BIGIP to be on a ready state
    bigip_wait:
      provider: "{{ provider }}"
    delegate_to: localhost

<<<<<<< HEAD

=======
>>>>>>> d0249d3c076f215d08406e227e520a8292cd0969
  - name: PUSH DO
    uri:
      url: "https://{{ inventory_hostname }}/mgmt/shared/declarative-onboarding"
      method: POST
      body: "{{ lookup('file', 'templates/do-standalone.json') }}"
      status_code: 202
      timeout: 500
      body_format: json
      force_basic_auth: yes
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: no
    delegate_to: localhost
    register: task_id

  - name: Wait unit DO is finished.
    uri:
      url: "https://{{ inventory_hostname }}/mgmt/shared/declarative-onboarding/task/{{ task_id.json.id }}"
      method: GET
      timeout: 30
      body_format: json
      force_basic_auth: yes
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: no
    delegate_to: localhost
    register: do_task_response
    changed_when: do_task_response.status == 200  
    retries: 120
    until: do_task_response.status == 200
    delay: 3

  - name: DO Provisioning failed
    fail:
      msg: "DoS Protection service de-activation failed with: {{ do_task_response.json.result.errors }}"
    when: do_task_response.status != 200 